[package]
name = "macro-package"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.11"
manyhow = { version = "0.11.4", features = ["darling"] }
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = "2.0.113"

[lints]
workspace = true
